create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  age_group text not null check (age_group in ('10-16','16+')),
  total_time numeric not null,
  errors integer not null default 0,
  final_score numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_age_group_score_idx
  on public.leaderboard(age_group, final_score, created_at);

alter table public.leaderboard enable row level security;

create policy "leaderboard_select_all"
on public.leaderboard for select
using (true);

create policy "leaderboard_insert_owner"
on public.leaderboard for insert
to authenticated
with check (auth.uid() = user_id);
